#!/bin/sh
shorthand="my"

if type "op" > /dev/null; then
  for i in {1..3}; do
    op list vaults &> /dev/null
    if [ $? -eq 0 ];
    then
        break 
    fi
    eval "$(echo | dmenu -c -p 'One Password Login' | op signin $shorthand)"
  done
else
    echo "One Password command line utility not found."
fi
